FROM golang:1.13

# Install development tools
#RUN npm install typescript -g

# set working directory
WORKDIR /app

# Copy project file
#COPY package*.json ./

# install ALL go_modules
#RUN npm install
RUN go get -u

# copy all project
COPY . .

# compile source code
RUN go build ./bin/run.go
