version: '3.3'

services:

  app:
    image: ${IMAGE:-app}
    ports:
      - "8080:8080"  
    depends_on:
      - mongo
      - postgres
      
    environment:
      - HTTP_PORT=8080
      - MONGO_ENABLED=true
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017"

  postgres:
    image: postgres:latest
    # container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    # ports:
    #   - "5432:5432"
