FROM golang:1.13

# set working directory
WORKDIR /app

# Copy project file
#COPY package*.json ./

# install ALL node_modules, including 'devDependencies'
#RUN npm install
RUN go get -u

# copy all project
COPY . .
 
CMD go test -v ./test/...