# Start with the golang v1.13 image
FROM golang:1.13

# Set a working directory
WORKDIR /app

# Copy the package files
COPY go.mod go.sum ./

# Install all go_modules
RUN go mod download

# Copy the entire project
COPY . .

# Build the project
RUN go build -o ./obj/app ./bin