version: '3.3'

services:

  app:
    image: ${IMAGE:-app}
    ports:
      - "8080:8080"  
    depends_on:
      - mongo
    environment:
      - HTTP_PORT=8080
      - MONGO_ENABLED=true
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
