FROM golang:1.13

# set working directory
WORKDIR /app

# copy package files
COPY go.mod go.sum ./

# install ALL go_modules
RUN go mod download

# copy all project
COPY . .

CMD go test -v ./test/...